heroku/python-getting-started

app.json

Missing app.json causes app setup API ( https://api.heroku.com/app-setups ) not to work.
same issue as: https://github.com/heroku/php-getting-started/issues/7

added app.json

---

requirements.txt

[https://www.djangoproject.com/download/#supported-versions](url)
Django 1.9 has been out of extended life support for exactly 3 months now. 1.11 works well on heroku.

update django version for support until at least 2020

---

runtime.txt

Bump Python patch version to stay up to date with the latest Python 3.7 version available on the platform.

bump version

---

hello/templates/index.html

Without this, you get an error: " 'staticfiles' is not a registered tag library"

Fix for static

---

runtime.txt

In `runtime.txt`, `python 3.7.6` was changed to `python 3.7.8`. Version 3.7.8 includes additional security patches over 3.7.6.

Update to Python 3.7.8 for security patches

---

hello/templates/db.html

{% load staticfiles %} and {% load admin_static %} were deprecated in Django 2.1, and removed in Django 3.0. [see last bullet here](https://docs.djangoproject.com/en/dev/releases/3.0/#features-removed-in-3-0)
Tried to follow the getting started guide and ran into this issue when going to the '/db' route. Would create a more consistent experience for all subsequent users for this guide in the future!

Change 'staticfiles' to 'static' with new Django version

---

README.md

Since the project was upgraded to 3.9 in #115.
Also fixes the redirect in the installing Python guide link.

README: Update required Python version to 3.9

---

Procfile

The gunicorn command line option `--log-file -` was renamed to `--error-logfile -` in gunicorn v0.13.0 in 2011:
https://github.com/benoitc/gunicorn/commit/66f7271c5f67bedc576382a4384604298e6180a0
In addition, in gunicorn v19.2 (released 2015-01-30), `--error-logfile` defaults to `-` so the option can be omitted entirely:
http://docs.gunicorn.org/en/latest/settings.html#errorlog

Remove redundant `--log-file` gunicorn flag

---

runtime.txt

https://www.python.org/downloads/release/python-395/
Closes GUS-W-9219520.

Update Python to 3.9.5

---

requirements.txt

`dj-database-url` v1.0.0 was just released:
https://github.com/jazzband/dj-database-url/releases/tag/v1.0.0
The only breaking change is dropping of Python 2.7 support, which doesn't affect this project.
Changes:
https://github.com/jazzband/dj-database-url/blob/master/CHANGELOG.md#v100-2022-18-06
https://github.com/jazzband/dj-database-url/compare/v0.5.0...v1.0.0

Update `dj-database-url` to 1.x

---

README.md

Once Heroku's free plans end, creating apps for the tutorial will count towards account Eco hours/credits/charges usage, so this needs to be made clear in the README.
This should not be merged until 28th November, when the plan changes take effect.
GUS-W-12008817.

Update README for ending of free plans

---

hello/tests.py

The example unit tests have been rewritten to actually test the app, and so they no longer use unnecessary setup boilerplate.

Improve example unit tests

---

app.json

Running the tests in debug mode means WhiteNoise uses its development mode file finder, which means collectstatic doesn't need to have been run first.
In CI either approach is equally valid, however, locally it's very easy to forget to run collectstatic, so we use the `--debug-mode` approach in `app.json` so users know about this trick when reading the codebase.

Use `--debug-mode` for tests instead of running collectstatic

---

gettingstarted/settings.py
gettingstarted/urls.py

The Django admin panel feature has been commented out, to improve security, and to reduce the number of static files that have to be processed during collectstatic. (Given that many people won't use the feature, and it requires additional user setup before it can be used anyway.)

Disable Django admin by default

---

gettingstarted/settings.py
requirements.txt

* Switch from the deprecated `STATICFILES_STORAGE` Django config option to `STORAGES`
* Add `whitenoise.runserver_nostatic` to `INSTALLED_APPS` so that WhiteNoise's runserver implementation is used instead of Django's default implementation, for improved dev-prod parity
* Enable `WHITENOISE_KEEP_ONLY_HASHED_FILES`, which means the original (un-hashed filename) copy of static assets are no longer unnecessarily stored in the slug. (This does mean all Django templates must use the `static` processor for asset URLs, but all of the templates in this guide do that already.)
* Use the `brotli` WhiteNoise package extra, so that the Brotli package ends up being installed, so that static assets can also be served using the more efficient Brotli compression (for browsers that support it, which is …

Improve WhiteNoise configuration

---

app.json
gettingstarted/settings.py

The Django secret key is no longer hardcoded to an example value, instead using a randomised value if the recommend env var is not set. The previous implementation could be insecure if users didn't set an explicit value, and also encouraged secrets being committed to source rather than the use of env vars.
The name of the env var has also been renamed from `SECRET_KEY` to `DJANGO_SECRET_KEY`.

Use a randomised Django secret key if one isn't set explicitly

---

Procfile
app.json
gettingstarted/settings.py
hello/views.py
requirements.txt

* The app no longer provisions a Postgres addon by default (since the Postgres adapter dependency in `requirements.txt` is commented out, which is what the Python buildpack uses to determine whether to auto-provision), so that it's possible to try the main part of the guide without incurring any additional charges beyond the eco dyno plan.
* The Postgres DB addon has been removed from `app.json` too, which prevents it from being auto-provisioned for Review Apps too.
* Help comments has been added to the `db` view function, to try and help prevent confusion due to errors on Heroku from the DB not being auto-provisioned.
* The Postgres adapter has been switched from `psycopg2` to `psycopg`, which counter-intuitively is newer (`psycopg` is the v3 implementation of the adapter). The binary …

Don't provision a Postgres database by default

---

Procfile.windows

Ensures that the PORT env var set automatically when running the `heroku local` command is honoured on Windows.
GUS-W-14137365.

Fix Procfile.windows so it honours `PORT` set by `heroku local`

---

requirements.txt

The `psycopg` package defaults to a pure Python implementation.
To opt into the faster C implementation, one has to use the `c` extra.
This differs from the `psycopg2` package (which contrary to the what the name suggests, is the older package), where the base package included the C implementation.
See:
https://www.psycopg.org/psycopg3/docs/basic/install.html#local-installation
https://www.psycopg.org/psycopg3/docs/api/pq.html#pq-impl
GUS-W-14292989.

Use the C implementation of psycopg

---

gettingstarted/settings.py

In cases where something other than the `DATABASE_URL` needs to be set, it was previously hard to know how to customise `dj-database-url`'s config, since the upstream docs don't mention the `env` option.
Now our default config passes an explicit value for `env` (which matches the default value for that argument), to improve discoverability.
In addition, the Heroku Postgres docs link has been updated to deep link to the env vars section, which explains when/why DB env vars will be given alternate colour-prefixed names.
Closes #221.

Improve discoverability of `dj-database-url`'s `env` option

---

gettingstarted/settings.py

The Dev Center guide instructs users running this project locally to visit `http://localhost:5001`, however, some users don't read the guide properly and instead use the URL output by gunicorn to the logs:
```
[2024-05-27 09:52:07 +0000] [1] [INFO] Listening at: http://0.0.0.0:5001 (1)
```
Django's default debug mode `ALLOWED_HOSTS` only includes `localhost` and `127.0.0.1` etc, so as a result using `0.0.0.0` would result in a `DisallowedHost` error:
https://docs.djangoproject.com/en/5.0/ref/settings/#allowed-hosts
According to RFC5735 `0.0.0.0` shouldn't be a routable IP, however, browsers and some other clients choose to treat it like localhost:
https://stackoverflow.com/a/55646032
Adding it to `ALLOWED_HOSTS` is safe, so we might as well do so to improve the UX when users don't follow …

Add `0.0.0.0` to non-production `ALLOWED_HOSTS`

---

gettingstarted/settings.py

The example app isn't currently using the admin, auth, sessions and messages features.
The config has been commented out rather than removed, to make it easier for users to re-enable if needed. (Particularly since some of the config is order dependant, such as `MIDDLEWARE`.)

Disable unused Django features

---

Procfile
gettingstarted/settings.py
gunicorn.conf.py

By default when the `PORT` env var is set, gunicorn binds to the IPv4 interface `0.0.0.0:$PORT`:
https://docs.gunicorn.org/en/stable/settings.html#bind
Now, we configure it to bind to the IPv6 interface `[::]:$PORT` instead, allowing the app to work in IPv6-only environments.
We don't have it bind to both the IPv4 and IPv6 interfaces, since otherwise on Linux by default gunicorn would fail to boot with:
```
[ERROR] connection to ('::', 5006) failed: [Errno 98] Address already in use
```
...and when binding to the IPv6 interface IPv4 connections will still work (so long as `IPV6_V6ONLY` hasn't been enabled).
If this strategy causes issues, we could always start using the `reuse_port` option, however, that makes the DX worse for the local development use-case (it's then possible to leave a …

Configure gunicorn to bind to the IPv6 interface

---

gunicorn.conf.py

gunicorn's default worker type is the `sync` worker, which is more suited to CPU/network-bandwidth bound workloads.
As such this switches to the thread-based `gthread` worker for improved request throughput performance for blocking I/O workloads - given that it's common for Heroku apps to make blocking requests to external APIs/datastores etc.
The threads count of 5 is somewhat arbitrary, but seemed to work well enough with rough benchmarking against a few different dyno sizes (where the process count will vary according to `WEB_CONCURRENCY`) and simulated workload types.
The `preload_app` option has also been enabled, which makes gunicorn load the app before the worker processes are forked, to reduce memory usage and boot times.
See: …

Switch to gunicorn's `gthread` worker type

---

app.json

* Remove the `image` field, since the `heroku.yml` languages feature was sunset some time ago, and the language docker images no longer exist.
* Add the `website` field so the Heroku Button deploy form links to the Getting started guide.
See:
https://devcenter.heroku.com/articles/heroku-button
https://devcenter.heroku.com/articles/app-json-schema

Update app.json metadata

---

gunicorn.conf.py

So that it's on one line and easier to include via the rundoc template for the getting started guide.

Clean up the gunicorn `bind` config

---

gunicorn.conf.py

* Explicitly enable the access log (since currently it's only enabled when using the classic Python buildpack, and not locally or when using the Python CNB).
* Customise the gunicorn access log format to make it use the Heroku logfmt style, and to improve which fields are included.
Format before:
```
2024-12-08T16:23:33.457957+00:00 app[web.1]: ::ffff:10.1.50.245 - - [08/Dec/2024:16:23:33 +0000] "GET / HTTP/1.1" 200 9585 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:134.0) Gecko/20100101 Firefox/134.0"
```
Format after:
```
2024-12-08T16:32:47.618296+00:00 app[web.1]: gunicorn method=GET path="/" status=200 duration=14ms request_id=e45f9c86-d6d8-4b79-937e-18c0b6bf859e fwd="123.456.789.0" user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:134.0) Gecko/20100101 …
```

Configure gunicorn access log

---

.env
gunicorn.conf.py

This saves having to manually restart gunicorn after making changes to the app in development when using `heroku local`.
See:
https://docs.gunicorn.org/en/stable/settings.html#reload
GUS-W-17614098.

Enable automatic gunicorn reloading in development

---

gunicorn.conf.py

This causes gunicorn to set `SO_REUSEPORT` on the listening socket, which helps ensure better request distribution between gunicorn workers and thus better performance.
We don't enable this in development, since it makes it harder to notice when duplicate gunicorn processes have accidentally been launched (eg in different terminals), since the "address already in use" error no longer occurs.
See:
https://docs.gunicorn.org/en/stable/settings.html#reuse-port
https://github.com/benoitc/gunicorn/pull/2938
https://lwn.net/Articles/542629/
GUS-W-17614363.

Enable gunicorn's `reuse_port` in production

---

gunicorn.conf.py

Since otherwise it interferes with `reload = True`.
See:
https://docs.gunicorn.org/en/stable/settings.html#reload
GUS-W-17614098.

Don't enable gunicorn's `preload_app` in development

---

gettingstarted/settings.py

Since by default full Django logs are only emitted when `DEBUG=True` (which otherwise makes diagnosing errors much harder in production):
https://docs.djangoproject.com/en/5.1/ref/logging/#default-logging-configuration
https://docs.djangoproject.com/en/5.1/howto/logging/
GUS-W-17618372.

Add a custom Django `LOGGING` configuration

---

.env
gettingstarted/settings.py

Previously `DEBUG` would be enabled in any environment that wasn't a Heroku app, including an OCI image built using the Python CNB. Instead we would rather such an image act closer to how the app will on Heroku.
(We also want as few Heroku-specific conditionals as possible.)
GUS-W-17623845.

Enable Django `DEBUG` in fewer scenarios

---

.env

Since otherwise when Django management commands like `manage.py runserver` are run via `heroku local`, the log buffering causes the server startup logs to not appear immediately.

Set `PYTHONUNBUFFERED=1` locally

---

gettingstarted/settings.py
gunicorn.conf.py

Using Django's `SECURE_SSL_REDIRECT`:
https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-SECURE_SSL_REDIRECT
Also configures gunicorn's `forwarded_allow_ips` setting to `"*"` so that gunicorn trusts the `X-Forwarded-Proto` header set by the Heroku Router during TLS termination, to ensure that HTTPS requests are correctly marked as secure in the WSGI metadata passed to the WSGI app (in this case, Django). See:
https://docs.gunicorn.org/en/stable/settings.html#forwarded-allow-ips
https://devcenter.heroku.com/articles/http-routing#heroku-headers
(Whilst the classic Python buildpack already configures this by setting the env var `FORWARDED_ALLOW_IPS`, the Python CNB doesn't yet do so, and it's clearer to have the config explicitly set in the app source.)
GUS-W-17482732.

Enable redirection of HTTP requests to HTTPS

---

gettingstarted/settings.py
requirements.txt

Since the Brotli dependency adds ~7-8MB (depending on arch) to the app image (along with having to download/install the wheel during the build), and isn't currently used by the Getting Started guide, since it doesn't have any static assets that are compressible.
```
$ ls -alh /layers/heroku_python/venv/lib/python3.13/site-packages/
...
-rwxr-xr-x  1 heroku heroku 7.2M Jan  1  1980 _brotli.cpython-313-aarch64-linux-gnu.so
```
```
$ ls -al /workspace/staticfiles/ 
total 16
drwxr-xr-x 2 heroku heroku 4096 Jan  1  1980 .
drwxrwxrwx 5 heroku heroku 4096 Jan  1  1980 ..
-rw-r--r-- 1 heroku heroku 2217 Jan  1  1980 lang-logo.019c8743b7cf.png
-rw-r--r-- 1 heroku heroku  100 Jan  1  1980 staticfiles.json
```
See:
https://whitenoise.readthedocs.io/en/latest/django.html#brotli-compression …

Remove Brotli dependency

---

gunicorn.conf.py

For consistency with the timeout chosen by other languages since #261 landed:
- https://github.com/heroku/heroku-buildpack-php/pull/823
- https://github.com/heroku/ruby-getting-started/pull/190
GUS-W-18319007.

Change the Keep-Alive idle timeout to 95 seconds
